### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by nr-kkenney**
* updated architecture documentation
* updated runbook documentation

Relates to: #757, #793

### CODE REVIEW

**Comment by jpvajda** [comment]
@nr-kkenney is this a PR you are still actively working on?

**Comment by nr-kkenney** [comment]
@jpvajda nope. i just let it sit since we thought it should wait until after we migrate. the work is done, just the merging needs to happen.

**Comment by jpvajda** [comment]
removing stale label as this will be done when we migrate to gatsby

**Review by LizBaker — DISMISSED** [review]

**Review by rudouglas — APPROVED** [review]
LGTM

**Pull request merged**
