### PR TITLE
Bump theme

### PR DESCRIPTION
**Pull request by roadlittledawn**
## Description

Bumps theme to latest version to bring in the new search XP, image links in new tab, and sending tessen events on feedback clicks

## Related issues / PRs

https://github.com/newrelic/gatsby-theme-newrelic/pull/375

### CODE REVIEW

**Comment by aswanson-nr** [comment]
@roadlittledawn Looks like the Jest snapshots need to be updated!

**Comment by roadlittledawn** [comment]
> @roadlittledawn Looks like the Jest snapshots need to be updated!

@aswanson-nr yep looking at that now

**Comment by zstix** [comment]
Looks like we've got a `z-index` problem:
Screen Shot 2021-05-19 at 11 34 17 AM

**Comment by roadlittledawn** [comment]
> Looks like we've got a `z-index` problem:
> Screen Shot 2021-05-19 at 11 34 17 AM

ooh nice catch. will look into that next

**Review by nr-kkenney — APPROVED** [review]
looks good. search is on top.

**Pull request merged**
