### PR TITLE
fix: updates theme and moves to yarn

### PR DESCRIPTION
**Pull request by jpvajda**
This PR bumps the theme to the most current version and also switches to Yarn over NPM.

### CODE REVIEW

**Comment by jpvajda** [comment]
It looks like there is more work to do on the pr.yml file as it uses NPM in a lot of places.

**Comment by jpvajda** [comment]
```Run npm ci
npm ERR! cipm can only install packages with an existing package-lock.json or npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or later to generate it, then try again.```

I think we just need to replace this with the yarn equivalent.  

https://stackoverflow.com/questions/58482655/what-is-the-closest-to-npm-ci-in-yarn

**Comment by jerelmiller** [comment]
Closing in favor of #689 

We'll need to do a bit more before we can move to yarn as a lot of the GitHub actions use `npm` right now. Let's do that separately from the theme update.

**Comment by jpvajda** [comment]
@jerelmiller I found that out when I did this work. 😓  but was definitely interested in taking it on.

**Pull request closed without merging**
