### PR TITLE
chore: bumps theme

### PR DESCRIPTION
**Pull request by jpvajda**
This PR bumps the theme which removes UTM params from the sign up button clicks, which should resolve some analytics problems.

### CODE REVIEW

**Comment by jpvajda** [comment]
Relates to newrelic/docs-website#1816

**Comment by jerelmiller** [comment]
Something is definitely off with the new version of the theme. Looks like this is also failing the build for the same reason as the dev site.

**Comment by jpvajda** [comment]
I'm looking into this error:

```
SiteSiteMetadata.utmSource provided incorrect OutputType: 'Object({
resolve: [function wrappedTracingResolver], extensions: Object({
createdFrom: "createResolvers" }) })'



  Error: SiteSiteMetadata.utmSource provided incorrect OutputType: 'Ob
  ject({ resolve: [function wrappedTracingResolve
```

**Comment by jpvajda** [comment]
Closing for this PR https://github.com/newrelic/opensource-website/pull/751

**Pull request closed without merging**
