### PR TITLE
[Snyk] Upgrade @mdx-js/mdx from 1.6.19 to 1.6.22

### PR DESCRIPTION
**Pull request by jerelmiller**
<h3>Snyk has created this PR to upgrade @mdx-js/mdx from 1.6.19 to 1.6.22.</h3>

:information_source: Keep your dependencies up-to-date. This makes it easier to fix existing vulnerabilities and to more quickly identify and fix newly disclosed vulnerabilities when they affect your project.
<hr/>

- The recommended version is **3 versions** ahead of your current version.
- The recommended version was released **3 months ago**, on 2020-12-01.

<details>
<summary><b>Release notes</b></summary>
<br/>
  <details>
    <summary>Package name: <b>@mdx-js/mdx</b></summary>
    <ul>
      <li>
        <b>1.6.22</b> - <a href="https://snyk.io/redirect/github/mdx-js/mdx/releases/tag/v1.6.22">2020-12-01</a></br><ul>
<li>Bump dependencies</li>
<li>Update documentation</li>
</ul>
      </li>
      <li>
        <b>1.6.21</b> - <a href="https://snyk.io/redirect/github/mdx-js/mdx/releases/tag/v1.6.21">2020-11-07</a></br><p>v1.6.21</p>
      </li>
      <li>
        <b>1.6.20</b> - <a href="https://snyk.io/redirect/github/mdx-js/mdx/releases/tag/v1.6.20">2020-11-07</a></br><p>v1.6.20</p>
      </li>
      <li>
        <b>1.6.19</b> - <a href="https://snyk.io/redirect/github/mdx-js/mdx/releases/tag/v1.6.19">2020-10-20</a></br><p>v1.6.19</p>
      </li>
    </ul>
    from <a href="https://snyk.io/redirect/github/mdx-js/mdx/releases">@mdx-js/mdx GitHub release notes</a>
  </details>
</details>

<details>
  <summary><b>Commit messages</b></summary>
  </br>
  <details>
    <summary>Package name: <b>@mdx-js/mdx</b></summary>
    <ul>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/510bae2580958598ae29047bf755b1a2ea26cf7e">510bae2</a> v1.6.22</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/6c1bff1a90f1d2393a597db472f4a71d62afcca4">6c1bff1</a> chore(deps): update dependency eslint-plugin-react to v7.21.5 (#1288)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/083e3fd2d1be10a3e1c9f5386f74aab8a7ee67a2">083e3fd</a> chore(deps): update dependency eslint-config-prettier to v6.15.0 (#1282)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/b5c31c10906e0bfc99d9b19bb443615b68d4d44e">b5c31c1</a> chore(deps): update dependency preact-render-to-string to v5.1.12 (#1310)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/a5941f02e6815d3013cdc025c332f0ed067fb12e">a5941f0</a> fix(deps): update dependency mdast-util-to-hast to v10 (#1293)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/5b7fb732c21da76dce5f8b83950a1616ed2f195d">5b7fb73</a> chore(deps): update dependency eslint-plugin-import to v2.22.1 (#1287)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/cd0843f14bd98e4f650948035c3212b565da3636">cd0843f</a> chore(deps): update dependency eslint to v7.14.0 (#1281)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/0c66a863ed78c91db866fa576db9d1b9123a0819">0c66a86</a> chore(deps): update dependency eslint-config-xo to v0.33.1 (#1303)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/60824eab5c57ef53c733977fa6e433611fbae939">60824ea</a> chore(deps): update dependency @ vue/test-utils to v1.1.1 (#1321)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/15922c8310fe0d6ce45b20e61f35442ddea49107">15922c8</a> chore(deps): update babel monorepo (#1301)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/4e93b8dbb42ed35832df23ae098947728bf14deb">4e93b8d</a> chore(deps): update dependency remark-preset-wooorm to v8 (#1306)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/22e6271455ef1fae77f38e99054fcc769f21f47e">22e6271</a> chore(deps): update dependency hast-util-select to v4.0.1 (#1322)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/8749cb8c74a4a259bba0b9c482bd4c4804f43923">8749cb8</a> chore(deps): update dependency yarn-deduplicate to v3.1.0 (#1323)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/d586a84b2057249d959a6bc36b8bdc70b981b896">d586a84</a> Add mdnext link</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/48642e9bacb41a278c701f5fc0f6a0a7e4f66ce7">48642e9</a> Add MDNEXT to projects page (#1309)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/02e7c8ca81eea44f027f16ee5543b9fb5fb5bf33">02e7c8c</a> fix(deps): update dependency @ emotion/core to v10.1.1 (#1324)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/83e6e81b9c276e7bed3c5014d22c55d08be21507">83e6e81</a> chore(deps): update dependency preact to v10.5.7 (#1334)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/7a9476c261aedae98347cde63a249c71a9f67bce">7a9476c</a> fix(deps): update dependency @ theme-ui/components to v0.3.4 (#1335)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/d1584841acda6e5dab45848eec0f80c17dd9d749">d158484</a> fix(deps): update dependency detab to v2.0.4 (#1336)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/c3555475c34eadc90fffc3dd6dde4fa367a5ebcb">c355547</a> fix(deps): update dependency gatsby-plugin-theme-ui to v0.3.4 (#1337)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/39252199cbdbd8bd276d1a410d78a333477ebead">3925219</a> Correct descriptions/tags in Table of components (#1331)</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/ed1999801cf370a8f081da29431d022f4b22ad28">ed19998</a> Fix &#x60;delete&#x60; -&gt; &#x60;del&#x60; in docs on typescript</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/889eb4b69b0aebdbd92afff4e16aac2db33e6c8b">889eb4b</a> Update &#x60;typescript.mdx&#x60;</li>
      <li><a href="https://snyk.io/redirect/github/mdx-js/mdx/commit/97ec1a8436100143c76d2ea1c28ec082c394379f">97ec1a8</a> v1.6.21</li>
    </ul>

   <a href="https://snyk.io/redirect/github/mdx-js/mdx/compare/a4fb84aa824b66545eacc60c50beef52f7d848f7...510bae2580958598ae29047bf755b1a2ea26cf7e">Compare</a>
  </details>
</details>
<hr/>

**Note:** *You are seeing this because you or someone else with access to this repository has authorized Snyk to open upgrade PRs.*

For more information:  

🧐 [View latest project report](https://app.snyk.io/org/github-newrelic/project/f888c3c2-125f-4ff7-a0c6-0181b3c27c8b?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🛠 [Adjust upgrade PR settings](https://app.snyk.io/org/github-newrelic/project/f888c3c2-125f-4ff7-a0c6-0181b3c27c8b/settings/integration?utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr)

🔕 [Ignore this dependency or unsubscribe from future upgrade PRs](https://app.snyk.io/org/github-newrelic/project/f888c3c2-125f-4ff7-a0c6-0181b3c27c8b/settings/integration?pkg&#x3D;@mdx-js/mdx&amp;utm_source&#x3D;github&amp;utm_medium&#x3D;upgrade-pr#auto-dep-upgrades)

### CODE REVIEW

**Review by jpvajda — APPROVED** [review]

**Review by jpvajda — CHANGES_REQUESTED** [review]
there are conflicts that need to be resolved

**Comment by guggerjulien** [comment]
C'est une arnaque

Le ven. 19 mars 2021 à 22:33, John P Vajda ***@***.***> a
écrit :

**Comment by zstix** [comment]
I had to mess with the lockfile to get this to resolve correctly. Theres a dependency that is relying on a dependency which is now outdated. The solution was to run `npm install --save --legacy-peer-deps`.

If someone could take review this (to double check it looks right), that would be great.

**Comment by jpvajda** [comment]
@zstix I did a quick visual check on the amplify preview link, site seems fine to me. That's a huge change but I assume it's due to the npm command you had to run.

**Review by jpvajda — APPROVED** [review]

**Pull request merged**
