### PR TITLE
Update gatsby-theme-newrelic to latest + other 

### LINKED ISSUE #712: Bump OSS Site Theme to newest version
the OSS site is really far beyond in our theme version at `1.16` we should bump this to newest theme version. In doing so we'll want to test the site as we made a lot of theme changes since.  `1.16`

### PR DESCRIPTION
**Pull request by jerelmiller**
Closes #712 

## Description

Update the Gatsby theme to the latest version + other Gatsby package updates. Minor adjustment to some text styles to better match with changes for the other sites.

### CODE REVIEW

**Comment by jpvajda** [comment]
@jerelmiller is this something we still want to merge in?

**Comment by jerelmiller** [comment]
Ah shoot, I forgot to come back to this. I’d like to fix the tests before merging. I think the version in this PR is also a little bit stale.

**Comment by jpvajda** [comment]
@jerelmiller I was also trying to bump the theme on the OSS Site to the most current version and also Move this site to YARN

https://github.com/newrelic/opensource-website/pull/717

I'm wondering what you want to do with this PR? I think it's becoming more stale as we've recently hooked up SNYK to this repo and have been merging in bumps in package dependencies.

**Comment by jerelmiller** [comment]
Let me take 30 min and just do the work to get this PR updated. Its got some additional work to make text styles fit better with the other sites, which I'd like to keep.

**Comment by jerelmiller** [comment]
@jpvajda alright this PR should be good to go!

**Comment by jpvajda** [comment]
@jerelmiller it looks like the jest check is failing..

https://github.com/newrelic/opensource-website/pull/689/checks?check_run_id=2145025383

**Pull request merged**
