### PR TITLE
Projects New Relic supports via GitHub Sponsors  - Homepage

### PR DESCRIPTION
**Pull request by Deizuca**
On the homepage I added an additional section below "Explore our projects". It is styled the same as the "Explore our projects" panel, with 8 randomly selected folks shown on the homepage and a "view all" link which takes you to https://github.com/orgs/newrelic/sponsoring.

The card for each person is their avatar, name, and bio from GitHub.

### CODE REVIEW

**Comment by jpvajda** [comment]
This PR is failing every check so we'll have to see what is going on here. Thanks for the contribution @Deizuca

**Comment by jpvajda** [comment]
```   "gatsby-source-github-api" threw an error while running the sourceNodes lifecycle:

    token is undefined

```

**Comment by Deizuca** [comment]
@jpvajda do you have any tips on how to resolve this issue?

**Comment by jpvajda** [comment]
@Deizuca it looks like you ran `npm-install` on this repository, this repo actually uses `Yarn` not `NPM`. So you'll want to remove the `package-lock.json` file and also remove the `yarn.lock` file. You might as well remove the `node_modules` folder as well, then re- run `yarn install`.  This will install all  necessary node modules, packages and generate a new yarn.lock file. 

You should then run `yarn start` and see what errors are generated in the console and focus on resolving those locally. If you are able to run the site locally with no errors and your change appears on the site as expected you can then push those changes and we'll see if the github checks pass.

**Comment by rudouglas** [comment]
@jpvajda i've been helping Daisy with some contribution work so i'll look into this

**Comment by jpvajda** [comment]
@rudouglas Great thank you!

**Comment by jpvajda** [comment]
I pulled this down and ran it locally, here are the error's I'm seeing in the console.

```
 ERROR #85923  GRAPHQL

There was an error in your GraphQL query:

Cannot query field "githubData" on type "Query".

If you don't expect "githubData" to exist on the type "Query" it is most likely a typo.
However, if you expect "githubData" to exist there are a couple of solutions to common problems:

- If you added a new data source and/or changed something inside gatsby-node.js/gatsby-config.js,
please try a restart of your development server
- The field might be accessible in another subfield, please try your query in GraphiQL and use the
GraphiQL explorer to see which fields you can query and what shape they have
- You want to optionally use your field "githubData" and right now it is not used anywhere.
Therefore Gatsby can't infer the type and add it to the GraphQL schema. A quick fix is to add at
least one entry with that field ("dummy content")

It is recommended to explicitly type your GraphQL schema if you want to use optional fields. This
way you don't have to add the mentioned "dummy content". Visit our docs to learn how you can define
 the schema for "Query":
https://www.gatsbyjs.com/docs/reference/graphql-data-layer/schema-customization#creating-type-defin
itions
```

and 

```
 ERROR #11321  PLUGIN

"gatsby-source-github-api" threw an error while running the sourceNodes lifecycle:

token is undefined

not finished source and transform nodes - 2.392s
```

**Comment by Deizuca** [comment]
I think it's because the api key is not there. Looks like it needs some error handling. I will try to work on it as soon as I can.

**Comment by nr-kkenney** [comment]
locally, this may work, but other contributors would need to define set GITHUB_API_TOKEN, and to have this build in the repo or gatsby cloud, we would need to supply the environment variable.
From this line:
```
process.env.GITHUB_API_TOKEN
```

**Comment by rudouglas** [comment]
Ok think i've found the issue here, got it to build locally, I had added the Github Token (which only has read:org permissions) to the Gatsby env settings, but it was called `GITHUB_API_KEY` instead of `GITHUB_API_TOKEN`

**Comment by rudouglas** [comment]
Ok i think i found the issue, the environment variable was named something else in Gatsby :facepalm: I also notice it's failing eslint and jest

If you run `yarn eslint-check`  it should tell you all of the issues to fix, or if you are using prettier in your editor that can automatically fix them

Then you need to run `yarn test:update`, which will create new snapshots for the tests and should pass the Jest workflow
then when you push those changes the site should rebuild and 🤞 not fail

**Comment by jpvajda** [comment]
This PR is starting to age a bit, so I applied the stale label. 🧀

**Comment by Deizuca** [comment]
Hi, I made a commit. It works fine as long as there is a Github API token. Ideally I'd like to work on making sure the build doesn't fail when there is no API key.

**Comment by jpvajda** [comment]
@Deizuca 👋 it looks like all checks are passing now, but I wanted to test this out to see how it actually will render on the site, when running locally I'm getting `"gatsby-source-github-api" threw an error while running the sourceNodes lifecycle:` error. So how are you visually testing this? Do you have some screenshots you can share of how this data will appear on the OSS site once deployed?

**Comment by Deizuca** [comment]
@jpvajda I created a personal access token on Github and used this command: export GITHUB_API_TOKEN=my personal token here. After that I ran yarn start. This is what I can see:
Screenshot 2021-11-12 at 10 31 30

**Comment by jpvajda** [comment]
This looks lovely.. Thanks again for contributing this feature! @Deizuca

**Review by jpvajda — APPROVED** [review]

**Comment by rudouglas** [comment]
This is so awesome thanks @Deizuca gonna merge to develop and make sure she builds in the ☁️

**Comment by rudouglas** [comment]
THis is now live https://opensource.newrelic.com/ 🥳

**Pull request merged**
