### PR TITLE
feat: upgrading to gatsby 4 [DONT MERGE]

### PR DESCRIPTION
**Pull request by jpvajda**
- Attempting to upgrade the OSS site to Gatsby 4. 
- This PR also bumps the theme on the OSS site. 
- this pr takes the approach about polyfills mentioned in this[ comment.](https://github.com/newrelic/docs-website/pull/5360#issue-1083278156)
- this pr adds createNodeField

### CODE REVIEW

**Comment by jpvajda** [comment]
This passes all checks now.

**Comment by aswanson-nr** [comment]
Something is up with this build, it's missing most of the projects on the preview build. Running a build locally to see what I can find

**Comment by aswanson-nr** [comment]
No resolution yet, this is what I'm seeing:
* `develop` branch
  * dev and prod builds show data correctly
* `gatsby4-upgrade` branch
  * dev builds and shows all projects
  * prod build does not show any projects except for the layouts

**Comment by aswanson-nr** [comment]
Okay, I know why but I haven't fixed it yet. We are doing [this](https://www.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#dont-mutate-nodes-outside-of-expected-apis) and need to swap over to using `createNodeField`

**Comment by jpvajda** [comment]
FWIW: when building locally I see this error, which I believe is related to the use of the gatsby-newrelic-plugin

` ERROR 

[@] winston-to-newrelic-logs: Error sending log data - Error: Request failed with status code 403

`

**Comment by jpvajda** [comment]
@rudouglas  may have some context into the error I am seeing with the build plugin

https://github.com/newrelic-experimental/gatsby-build-newrelic/issues/30

**Comment by jpvajda** [comment]
This PR is helpful for the suggestion @aswanson-nr  made https://github.com/gatsbyjs/gatsby/pull/33715

**Comment by jpvajda** [comment]
I made a change to use the `createNodeField` but the projects still aren't loading.. 🤔

**Comment by jpvajda** [comment]
I tried a different approach with the use of `createNodeField` what is interesting is locally I can load all the projects but when viewing the site on the preview build the projects do not load.

**Pull request closed without merging**
