### PR TITLE
chore: add nrql status widget project (custom viz)

### PR DESCRIPTION
**Pull request by Kav91**
Add NRQL Status Widget (custom dashboard viz) to projects.

cc/ @caylahamann

### CODE REVIEW

**Review by jpvajda — APPROVED** [review]
LGTM

**Comment by jpvajda** [comment]
I saw @caylahamann  in the comments but this looks ready to merge i tested the amplify preview.

**Comment by jpvajda** [comment]
One `nit` on this is the use of `feat` vs. `chore` in the commit message. I'd say this is more of chore based on the definition here:

https://github.com/newrelic/opensource-website/blob/develop/.github/pull_request_template.md

**Comment by Kav91** [comment]
@jpvajda just added @caylahamann as an fyi since it was mentioned to contribute more in the slack thread.
If we can merge that would be great!

Re. chore will keep it in mind for next PR, didn't realize there was specifics. Been using feat: for similar purposes in other projects so was habit for me.

**Review by caylahamann — APPROVED** [review]

**Comment by caylahamann** [comment]
I'm going to merge it in!

**Pull request merged**
