### PR TITLE
feat: added gatsby-build-newrelic

### PR DESCRIPTION
**Pull request by jpvajda**
This PR adds configuration to run  gatsby-build-newrelic on the OSS Site

### CODE REVIEW

**Comment by rudouglas** [comment]
@jpvajda doing some testing here with branch versions of the plugin

**Comment by rudouglas** [comment]
I got this working again @jpvajda don't forget to add the Environment Variables to `develop` and main in Gatsby Cloud before

**Comment by jpvajda** [comment]
@rudouglas not sure why this is failing again? I added the env variables to develop and main site branches...

**Comment by jpvajda** [comment]
All the builds are failing again, so I'm going to remove the env variables from Main / Develop as I don't want to block a build from succeeding.

**Comment by jpvajda** [comment]
Actually all I had to do was remove the variable for 

`GATSBY_OPEN_TRACING_CONFIG_FILE="node_modules/gatsby-build-newrelic/zipkin-local.js"`

And it builds fine.. 🤷

**Comment by rudouglas** [comment]
@jpvajda i noticed another issue with the plugin which is fixed now so this is building good now

**Review by rudouglas — APPROVED** [review]

**Pull request merged**
